/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Legacy colors preserved for backwards compatibility
        sidebar: {
          bg: '#0f1117',
          hover: '#1a1d27',
          active: '#1e2235',
          border: '#1e2235',
          text: '#8b92a5',
          textActive: '#e8eaf0',
        },
        brand: {
          DEFAULT: '#6366f1',
          light: '#818cf8',
          dark: '#4f52c8',
        },
        border: {
          DEFAULT: '#e4e7ef',
          light: '#f0f2f7',
        },

        // Warm Editorial Workspace Design System (DESIGN.md)
        'inverse-on-surface': '#f4f0e8',
        'primary-container': '#e6a219',
        'on-background': '#1c1c17',
        'inverse-surface': '#31302b',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#604100',
        'on-secondary-container': '#656467',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f3eb',
        'on-primary-fixed': '#281900',
        background: '#fdf9f1',
        'tertiary-fixed-dim': '#9dd2b8',
        surface: {
          DEFAULT: '#fdf9f1',
          base: '#fdf9f1',
          secondary: '#f8f9fc',
          tertiary: '#f1f3f8',
        },
        outline: '#837562',
        'tertiary-container': '#86baa1',
        'error-container': '#ffdad6',
        'on-primary-container': '#5a3c00',
        'surface-bright': '#fdf9f1',
        'surface-container': '#f1ede6',
        'on-primary': '#ffffff',
        primary: {
          DEFAULT: '#7f5700',
          honey: '#e6a219',
          hover: '#f5be38',
        },
        'secondary-container': '#e4e1e6',
        'on-secondary-fixed': '#1b1b1e',
        'on-surface-variant': '#514534',
        tertiary: '#366853',
        'on-secondary-fixed-variant': '#47464a',
        'secondary-fixed-dim': '#c8c5ca',
        'outline-variant': '#d5c4ae',
        'on-tertiary-container': '#174b38',
        'surface-container-high': '#ece8e0',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e6e2da',
        'inverse-primary': '#ffba3d',
        secondary: '#5f5e61',
        'on-surface': '#1c1c17',
        'primary-fixed': '#ffdeae',
        'on-tertiary-fixed-variant': '#1c4f3c',
        'surface-tint': '#7f5700',
        'on-secondary': '#ffffff',
        'surface-dim': '#dddad2',
        'primary-fixed-dim': '#ffba3d',
        'on-tertiary-fixed': '#002115',
        'surface-variant': '#e6e2da',
        error: '#ba1a1a',
        'secondary-fixed': '#e4e1e6',
        'tertiary-fixed': '#b8eed3',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'system-ui', 'sans-serif'],
        serif: ['Newsreader', 'Georgia', 'serif'],
        newsreader: ['Newsreader', 'Georgia', 'serif'],
        jakarta: ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl': ['Newsreader', 'Georgia', 'serif'],
        'headline-lg': ['Newsreader', 'Georgia', 'serif'],
        'headline-md': ['Newsreader', 'Georgia', 'serif'],
        'headline-sm': ['Newsreader', 'Georgia', 'serif'],
        'display-stat': ['Newsreader', 'Georgia', 'serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        '2xs': '0.65rem',
        'display-stat': ['48px', { lineHeight: '52px', letterSpacing: '-0.025em', fontWeight: '500' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['17px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        gutter: '1.25rem',
        'gutter-lg': '1.75rem',
        margin: '1.5rem',
        'margin-lg': '2.5rem',
      },
    },
  },
  plugins: [],
};
